services:
  astroserver:
    build:
      context: .
      dockerfile: Dockerfile.amd64
    # image: ghcr.io/joejoetv/astrotuxlauncher:master
    command: ["start"]
    tty: true
    stdin_open: true
    ports:
      - "7777:7777/udp"
    volumes:
      - ./AstroneerServer:/app/AstroneerServer
      - ./.wine:/root/.wine
      - type: bind
        source: ./launcher.toml
        target: /app/launcher.toml