FROM ghcr.io/unusualnorm/winebox:main

RUN apt-get update && apt-get install -y \    
        git python3 python3-pip \
    && apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt ./
RUN pip3 install -r requirements.txt

COPY . .
ENTRYPOINT ["python3", "AstroTuxLauncher.py"]